language: node_js
node_js:
  - "5"
  - "4.4.3"
  - "0.12"
  - "0.11"
  - "0.10"
script: "npm run-script test-cover"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"